spring.application.name=time_calculator
spring.datasource.url=jdbc:postgresql://10.8.135.131:5432/odoo12_ptap
spring.datasource.username=odoo12
spring.datasource.password=jklasd4


#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=Am290703

metabase.url=https://dashboard.it.ptap.co.id
metabase.secret=4dfb46604316943a101e8884f50ccf229f680c03eeec6b1dfd42026a072bc031
metabase.dashboard.id=1

jwt.secret=bfFWOwnk8yhfjvVIGO8KP6E0Ixomj70IvE8mrLq3rIs
jwt.expiration=7200000
jwt.issuer=time-calculator-api

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.jpa.open-in-view=false
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8089
